package com.mycompany.a3.Telas;

import com.mycompany.a3.Main.Projeto;
import com.mycompany.a3.Main.Servidor;
import java.util.ArrayList;

public class telaVizualicaoProjetos extends javax.swing.JFrame {

    Projeto[] Projetos;
    Projeto[] Paginas;
    int PaginaPresente = 0;
    
    public telaVizualicaoProjetos() {
        initComponents();
        
        Projetos = Servidor.GetProjetos();
        
        if (Projetos == null || Projetos.length == 0)
        {
            this.dispose();
            return;
        }
        
        Paginas = Projetos;
        
        MudarPagina(0);
        
        telaVizualicaoProjetos tvp = this;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                tvp.setVisible(true);
            }
        });
    }
    
    private void MudarPagina (int pagina)
    {
        PaginaPresente = pagina;
        
        Projeto p = Paginas[pagina];
        
        Nome.setText(p.Nome);
        Descricao.setText(p.Descricao);
        Autor.setText(p.UsuarioProprietario);
        
        ContadorPagina.setText(Integer.toString(pagina + 1) + "/" + Integer.toString(Paginas.length));
        
        ResetarUI();
    }
    
    private void ResetarUI ()
    {
        Salvar.setVisible(false);
        Cancelar.setVisible(false);
        Criar.setVisible(false);
        Descartar.setVisible(false);
        Proximo.setVisible(true);
        Anterior.setVisible(true);
        IndAutor.setVisible(true);
        Autor.setVisible(true);
        ContadorPagina.setVisible(true);
        CriarProjeto.setVisible(true);
        Nome.setEditable(false);
        Descricao.setEditable(false);
        bRequisitos.setVisible(true);
        Pesquisar.setVisible(true);
        BarraPesquisa.setVisible(true);
        
        boolean temPermissao = Servidor.MeuUsuario.ID == Paginas[PaginaPresente].IDProprietario || Servidor.MeuUsuario.Permissao > 0;
        
        Editar.setVisible(temPermissao);
        Usuarios.setVisible(Servidor.MeuUsuario.Permissao > 0);
        
        Deletar.setVisible(temPermissao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDashBoardProjetos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Nome = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        IndAutor = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Autor = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        Descricao = new javax.swing.JTextPane();
        Proximo = new javax.swing.JButton();
        Anterior = new javax.swing.JButton();
        ContadorPagina = new javax.swing.JLabel();
        bRequisitos = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        Salvar = new javax.swing.JButton();
        CriarProjeto = new javax.swing.JButton();
        Criar = new javax.swing.JButton();
        Descartar = new javax.swing.JButton();
        Usuarios = new javax.swing.JButton();
        Deletar = new javax.swing.JButton();
        BarraPesquisa = new javax.swing.JTextField();
        Pesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelDashBoardProjetos.setText("Gestão do Projeto");

        jLabel1.setText("Nome:");

        Nome.setEditable(false);
        jScrollPane1.setViewportView(Nome);

        jLabel2.setText("Descrição:");

        IndAutor.setText("Autor:");

        Autor.setEditable(false);
        jScrollPane2.setViewportView(Autor);

        Descricao.setEditable(false);
        Descricao.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane3.setViewportView(Descricao);
        Descricao.getAccessibleContext().setAccessibleName("");

        Proximo.setText("Próximo");
        Proximo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProximoMouseClicked(evt);
            }
        });

        Anterior.setText("Anterior");
        Anterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnteriorMouseClicked(evt);
            }
        });

        ContadorPagina.setText("1/10");

        bRequisitos.setText("Requisitos");
        bRequisitos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bRequisitosMouseClicked(evt);
            }
        });
        bRequisitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRequisitosActionPerformed(evt);
            }
        });

        Editar.setText("Editar");
        Editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarMouseClicked(evt);
            }
        });
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelarMouseClicked(evt);
            }
        });

        Salvar.setText("Salvar");
        Salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalvarMouseClicked(evt);
            }
        });
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });

        CriarProjeto.setText("Criar Projeto");
        CriarProjeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CriarProjetoMouseClicked(evt);
            }
        });

        Criar.setText("Criar");
        Criar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CriarMouseClicked(evt);
            }
        });

        Descartar.setText("Descartar");
        Descartar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DescartarMouseClicked(evt);
            }
        });

        Usuarios.setText("Usuários");
        Usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsuariosMouseClicked(evt);
            }
        });

        Deletar.setText("Deletar");
        Deletar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeletarMouseClicked(evt);
            }
        });

        BarraPesquisa.setText("Por favor digite tags com ', ' entre elas.");

        Pesquisar.setText("Pesquisar");
        Pesquisar.setActionCommand("Pesquisar");
        Pesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PesquisarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Anterior)
                                .addGap(162, 162, 162)
                                .addComponent(ContadorPagina)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Proximo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Usuarios)
                                .addGap(134, 134, 134)
                                .addComponent(Deletar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CriarProjeto)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(IndAutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(407, 407, 407)
                                .addComponent(Cancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bRequisitos)
                                    .addComponent(Editar)
                                    .addComponent(Salvar)
                                    .addComponent(Criar)
                                    .addComponent(Descartar)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(labelDashBoardProjetos)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Pesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BarraPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CriarProjeto)
                    .addComponent(Usuarios)
                    .addComponent(Deletar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BarraPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pesquisar))
                .addGap(24, 24, 24)
                .addComponent(labelDashBoardProjetos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IndAutor))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Criar)
                        .addGap(11, 11, 11)
                        .addComponent(Editar)
                        .addGap(5, 5, 5)
                        .addComponent(Descartar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bRequisitos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Salvar)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cancelar)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Proximo)
                    .addComponent(Anterior)
                    .addComponent(ContadorPagina))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRequisitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRequisitosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bRequisitosActionPerformed

    private void AnteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnteriorMouseClicked
        if (!(PaginaPresente - 1 < 0)) MudarPagina(PaginaPresente - 1);
    }//GEN-LAST:event_AnteriorMouseClicked

    private void ProximoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProximoMouseClicked
        if (PaginaPresente + 1 < Paginas.length) MudarPagina(PaginaPresente + 1);
    }//GEN-LAST:event_ProximoMouseClicked

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditarActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalvarActionPerformed

    private void EditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseClicked
        Editar.setVisible(false);
        bRequisitos.setVisible(false);
        Salvar.setVisible(true);
        Cancelar.setVisible(true);
        Nome.setEditable(true);
        Descricao.setEditable(true);
        Deletar.setVisible(false);
    }//GEN-LAST:event_EditarMouseClicked

    private void SalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarMouseClicked
        Projeto projetoAtual = Paginas[PaginaPresente];
        
        Projeto p = Servidor.EditarProjeto(projetoAtual.ID, Nome.getText(), Descricao.getText());
        
        if (p != null)
        {
            projetoAtual.Nome = p.Nome;
            projetoAtual.Descricao = p.Descricao;
        }
            
        MudarPagina(PaginaPresente);
    }//GEN-LAST:event_SalvarMouseClicked

    private void CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarMouseClicked
        MudarPagina(PaginaPresente);
    }//GEN-LAST:event_CancelarMouseClicked

    private void CriarProjetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CriarProjetoMouseClicked
        Criar.setVisible(true);
        Descartar.setVisible(true);
        Editar.setVisible(false);
        CriarProjeto.setVisible(false);
        IndAutor.setVisible(false);
        Autor.setVisible(false);
        Nome.setEditable(true);
        Descricao.setEditable(true);
        ContadorPagina.setVisible(false);
        Proximo.setVisible(false);
        Anterior.setVisible(false);
        bRequisitos.setVisible(false);
        Deletar.setVisible(false);
        Pesquisar.setVisible(false);
        BarraPesquisa.setVisible(false);
        
        Nome.setText("");
        Descricao.setText("");
    }//GEN-LAST:event_CriarProjetoMouseClicked

    private void CriarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CriarMouseClicked
        Servidor.CriarProjeto(Nome.getText(), Descricao.getText());
        
        new telaVizualicaoProjetos();
        this.dispose();
    }//GEN-LAST:event_CriarMouseClicked

    private void DescartarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescartarMouseClicked
        MudarPagina (PaginaPresente);
    }//GEN-LAST:event_DescartarMouseClicked

    private void bRequisitosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bRequisitosMouseClicked
        new cadastroContinuacaoRequisitos(Paginas[PaginaPresente].ID, Servidor.MeuUsuario.ID == Paginas[PaginaPresente].IDProprietario || Servidor.MeuUsuario.Permissao > 0);
    }//GEN-LAST:event_bRequisitosMouseClicked

    private void UsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuariosMouseClicked
        new gestaoDeUsuario();
    }//GEN-LAST:event_UsuariosMouseClicked

    private void DeletarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletarMouseClicked
        Servidor.RemoverProjeto(Paginas[PaginaPresente].ID);
        
        new telaVizualicaoProjetos();
        this.dispose();
    }//GEN-LAST:event_DeletarMouseClicked

    private void PesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PesquisarMouseClicked
        int[] resultado = Servidor.PesquisarProjetos(BarraPesquisa.getText().split(", "));
        
        if (resultado != null && resultado.length > 0)
        {
            var paginas = new ArrayList<Projeto>();
            
            for (int i = 0; i< resultado.length; ++i)
            {
                int IDprojeto = resultado[i];
                
                for (int o = 0; o< Projetos.length; ++o)
                {
                    if (Projetos[o].ID == IDprojeto)
                    {
                        paginas.add(Projetos[o]);
                        break;
                    }
                }
            }
            
            Paginas = paginas.toArray(new Projeto[0]);
            
            MudarPagina(0);
        }
    }//GEN-LAST:event_PesquisarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaVizualicaoProjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaVizualicaoProjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaVizualicaoProjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaVizualicaoProjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        new telaVizualicaoProjetos();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anterior;
    private javax.swing.JTextPane Autor;
    private javax.swing.JTextField BarraPesquisa;
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel ContadorPagina;
    private javax.swing.JButton Criar;
    private javax.swing.JButton CriarProjeto;
    private javax.swing.JButton Deletar;
    private javax.swing.JButton Descartar;
    private javax.swing.JTextPane Descricao;
    private javax.swing.JButton Editar;
    private javax.swing.JLabel IndAutor;
    private javax.swing.JTextPane Nome;
    private javax.swing.JButton Pesquisar;
    private javax.swing.JButton Proximo;
    private javax.swing.JButton Salvar;
    private javax.swing.JButton Usuarios;
    private javax.swing.JButton bRequisitos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelDashBoardProjetos;
    // End of variables declaration//GEN-END:variables
}
